export const MCP_ERROR_CODES = {
  ERR_PAYMENT_REJECTED: 'ERR_PAYMENT_REJECTED',
  ERR_INSUFFICIENT_BALANCE: 'ERR_INSUFFICIENT_BALANCE',
  ERR_EXPIRED_AUTHORISATION: 'ERR_EXPIRED_AUTHORISATION',
  ERR_MISSING_TRUSTLINE: 'ERR_MISSING_TRUSTLINE',
  ERR_SERVICE_UNREACHABLE: 'ERR_SERVICE_UNREACHABLE',
  ERR_NO_RESULTS: 'ERR_NO_RESULTS',
  ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
  ERR_INTERNAL_FAILURE: 'ERR_INTERNAL_FAILURE'
} as const;

export type McpErrorCode = keyof typeof MCP_ERROR_CODES;

export interface McpErrorResponse {
  isError: true;
  code: McpErrorCode;
  reason: string;
}
